User flow
sharmine-s/acebook-airbenders pull request #13
Opened 2023-06-09 11:09 UTC by camybish

- Added refresh page function on posts, activates once newPost is submitted
- Added conditional to catch invalid tokens when heading to /posts

2023-06-09 12:58 UTC, camybish commented
If user accesses /posts page without a valid token, a loader now shows before redirecting to /login (can be seen if internet is slow).

2023-06-09 15:52 UTC, wimdavies approved these changes
nice

2023-06-09 16:29 UTC, sharmine-s requested changes
Please include a way to handle the scenario where no posts exist in the DB as it is just infinitely loading in this case currently

2023-06-12 09:12 UTC, sharmine-s approved these changes

2023-06-12 09:20 UTC, merged