Post liking capabilities
sharmine-s/acebook-airbenders pull request #14
Opened 2023-06-09 13:21 UTC by michael-szczepanski

1. .DS_Store added to .gitignore (I will stop doing this eventually, I promise)

Backend
1. Added a new method to PostController that currently only updates the likes field in the database
2. Added likes field to Post model
3. A patch route added to Post router

Frontend
4. a jwt_decoder package installed and used to retrieve and store userId in Feed from the token
5. Post component recreated from scratch with a function added to update the likes field
6. Slightly updated the html code for the Post component to display the button and number of likes

2023-06-09 15:47 UTC, sarahc-dev approved these changes
Amazing. Love it!

2023-06-09 15:53 UTC, ChristieGriffiths reviewed
Great job!

2023-06-09 16:29 UTC, wimdavies requested changes
Incorporate FE component Post.js  `post` s into one

2023-06-09 16:29 UTC, wimdavies commented on frontend/src/components/post/Post.js
Double Post issue

2023-06-11 19:41 UTC, michael-szczepanski commented on frontend/src/components/post/Post.js
Hopefully resolved now.

2023-06-12 09:12 UTC, wimdavies approved these changes
Kosher.

2023-06-12 09:13 UTC, merged